### ISSUE TITLE
Crash in analytzer when I change sample rate

### ISSUE THREAD

**Issue by squinkylabs** [bogaudio/BogaudioModules#166]
I'm running interzone into the freq analyzer at mas RS (768 k?) . Then I change the sample rate to 44.1k and it crashes every single time:

```

Thread 1 received signal SIGSEGV, Segmentation fault.
0x0000000067ece175 in bogaudio::AnalyzerDisplay::drawGraph (
    freqPlot=bogaudio::AnalyzerTypes::LOG_FP,
    ampPlot=bogaudio::AnalyzerTypes::DECIBELS_80_AP, rangeMaxHz=384000,
    rangeMinHz=0, strokeWidth=<optimized out>, color=...,
    bins=<synthetic pointer>..., args=..., this=0x1afd4a90)
    at src/analyzer_base.hpp:188
188                     float at(int i) override { return _bins[i]; }
(gdb) bt
#0  0x0000000067ece175 in bogaudio::AnalyzerDisplay::drawGraph (
    freqPlot=bogaudio::AnalyzerTypes::LOG_FP,
    ampPlot=bogaudio::AnalyzerTypes::DECIBELS_80_AP, rangeMaxHz=384000,
    rangeMinHz=0, strokeWidth=<optimized out>, color=...,
    bins=<synthetic pointer>..., args=..., this=0x1afd4a90)
    at src/analyzer_base.hpp:188
#1  bogaudio::AnalyzerDisplay::draw (this=0x1afd4a90, args=...)
    at src/analyzer_base.cpp:500
#2  0x0000000000000000 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

**Comment by mdemanett** [comment]
Pushed a change that should fix it.

**Comment by squinkylabs** [comment]
seems good now. tx!
